<template>
    <div class="text--wrapper">
        <slot>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam voluptates inventore quae recusandae, ullam non nam atque iure dolor ut laboriosam ipsa omnis impedit, placeat nemo labore quos distinctio! Alias?</slot>
    </div>
</template>

<style scoped>
.text--wrapper {

    padding-top: 3em;
    width: 30%;
    height: auto;
    color: #fff;
    margin: 0 auto;
    text-align: left;
    font-family:'Courier New', Courier, monospace;
}

</style>